db:
  image: postgres
web:
  build: .
  command: manage runserver 0.0.0.0:8000
  environment:
    - SETTINGS=settings_compose
    - SECRET_KEY=docker-compose-secr3t
  volumes:
    - .:/app/
  ports:
    - "8000:8000"
  links:
    - db
