# Generated by Django 3.2.16 on 2023-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description_html',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_html',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default='no title', max_length=256),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='extension',
            field=models.CharField(default='jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='photo',
            name='reticulum_key',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='no title', max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
