# Generated by Django 3.2.16 on 2023-02-06 10:44

import markdown
from django.db import migrations


def forwards(apps, schema_editor):
    Album = apps.get_model('main', 'Album')
    for album in Album.objects.all():
        album.description_html = markdown.markdown(album.description)
        album.save()
    Photo = apps.get_model('main', 'Photo')
    for photo in Photo.objects.all():
        photo.description_html = markdown.markdown(photo.description)
        photo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230206_1030'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
